// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: planetmintgo/dao/distribution_order.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DistributionOrder struct {
	DaoAddr         string `protobuf:"bytes,1,opt,name=daoAddr,proto3" json:"daoAddr,omitempty"`
	DaoAmount       string `protobuf:"bytes,2,opt,name=daoAmount,proto3" json:"daoAmount,omitempty"`
	DaoTxID         string `protobuf:"bytes,3,opt,name=daoTxID,proto3" json:"daoTxID,omitempty"`
	InvestorAddr    string `protobuf:"bytes,4,opt,name=investorAddr,proto3" json:"investorAddr,omitempty"`
	InvestorAmount  string `protobuf:"bytes,5,opt,name=investorAmount,proto3" json:"investorAmount,omitempty"`
	InvestorTxID    string `protobuf:"bytes,6,opt,name=investorTxID,proto3" json:"investorTxID,omitempty"`
	PopAddr         string `protobuf:"bytes,7,opt,name=popAddr,proto3" json:"popAddr,omitempty"`
	PopAmount       string `protobuf:"bytes,8,opt,name=popAmount,proto3" json:"popAmount,omitempty"`
	PopTxID         string `protobuf:"bytes,9,opt,name=popTxID,proto3" json:"popTxID,omitempty"`
	FirstPop        int64  `protobuf:"varint,10,opt,name=firstPop,proto3" json:"firstPop,omitempty"`
	LastPop         int64  `protobuf:"varint,11,opt,name=lastPop,proto3" json:"lastPop,omitempty"`
	Proposer        string `protobuf:"bytes,12,opt,name=proposer,proto3" json:"proposer,omitempty"`
	EarlyInvAddr    string `protobuf:"bytes,13,opt,name=earlyInvAddr,proto3" json:"earlyInvAddr,omitempty"`
	EarlyInvAmount  string `protobuf:"bytes,14,opt,name=earlyInvAmount,proto3" json:"earlyInvAmount,omitempty"`
	EarlyInvTxID    string `protobuf:"bytes,15,opt,name=earlyInvTxID,proto3" json:"earlyInvTxID,omitempty"`
	StrategicAddr   string `protobuf:"bytes,16,opt,name=strategicAddr,proto3" json:"strategicAddr,omitempty"`
	StrategicAmount string `protobuf:"bytes,17,opt,name=strategicAmount,proto3" json:"strategicAmount,omitempty"`
	StrategicTxID   string `protobuf:"bytes,18,opt,name=strategicTxID,proto3" json:"strategicTxID,omitempty"`
}

func (m *DistributionOrder) Reset()         { *m = DistributionOrder{} }
func (m *DistributionOrder) String() string { return proto.CompactTextString(m) }
func (*DistributionOrder) ProtoMessage()    {}
func (*DistributionOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bd326325e0d716d, []int{0}
}
func (m *DistributionOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DistributionOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DistributionOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DistributionOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistributionOrder.Merge(m, src)
}
func (m *DistributionOrder) XXX_Size() int {
	return m.Size()
}
func (m *DistributionOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DistributionOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DistributionOrder proto.InternalMessageInfo

func (m *DistributionOrder) GetDaoAddr() string {
	if m != nil {
		return m.DaoAddr
	}
	return ""
}

func (m *DistributionOrder) GetDaoAmount() string {
	if m != nil {
		return m.DaoAmount
	}
	return ""
}

func (m *DistributionOrder) GetDaoTxID() string {
	if m != nil {
		return m.DaoTxID
	}
	return ""
}

func (m *DistributionOrder) GetInvestorAddr() string {
	if m != nil {
		return m.InvestorAddr
	}
	return ""
}

func (m *DistributionOrder) GetInvestorAmount() string {
	if m != nil {
		return m.InvestorAmount
	}
	return ""
}

func (m *DistributionOrder) GetInvestorTxID() string {
	if m != nil {
		return m.InvestorTxID
	}
	return ""
}

func (m *DistributionOrder) GetPopAddr() string {
	if m != nil {
		return m.PopAddr
	}
	return ""
}

func (m *DistributionOrder) GetPopAmount() string {
	if m != nil {
		return m.PopAmount
	}
	return ""
}

func (m *DistributionOrder) GetPopTxID() string {
	if m != nil {
		return m.PopTxID
	}
	return ""
}

func (m *DistributionOrder) GetFirstPop() int64 {
	if m != nil {
		return m.FirstPop
	}
	return 0
}

func (m *DistributionOrder) GetLastPop() int64 {
	if m != nil {
		return m.LastPop
	}
	return 0
}

func (m *DistributionOrder) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *DistributionOrder) GetEarlyInvAddr() string {
	if m != nil {
		return m.EarlyInvAddr
	}
	return ""
}

func (m *DistributionOrder) GetEarlyInvAmount() string {
	if m != nil {
		return m.EarlyInvAmount
	}
	return ""
}

func (m *DistributionOrder) GetEarlyInvTxID() string {
	if m != nil {
		return m.EarlyInvTxID
	}
	return ""
}

func (m *DistributionOrder) GetStrategicAddr() string {
	if m != nil {
		return m.StrategicAddr
	}
	return ""
}

func (m *DistributionOrder) GetStrategicAmount() string {
	if m != nil {
		return m.StrategicAmount
	}
	return ""
}

func (m *DistributionOrder) GetStrategicTxID() string {
	if m != nil {
		return m.StrategicTxID
	}
	return ""
}

func init() {
	proto.RegisterType((*DistributionOrder)(nil), "planetmintgo.dao.DistributionOrder")
}

func init() {
	proto.RegisterFile("planetmintgo/dao/distribution_order.proto", fileDescriptor_2bd326325e0d716d)
}

var fileDescriptor_2bd326325e0d716d = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x3d, 0x6f, 0x22, 0x31,
	0x10, 0x65, 0x0f, 0x8e, 0x0f, 0x1f, 0x9f, 0x5b, 0x59, 0xa7, 0xd3, 0x0a, 0xa1, 0x53, 0x44, 0x8a,
	0xb0, 0x45, 0x7e, 0x41, 0x22, 0x1a, 0xaa, 0x44, 0x28, 0x55, 0x9a, 0xc8, 0x60, 0x67, 0x63, 0x09,
	0x76, 0x2c, 0xaf, 0x41, 0xf0, 0x2f, 0xf2, 0xb3, 0x52, 0x52, 0xa6, 0x4b, 0x04, 0x7f, 0x24, 0xf2,
	0x18, 0xcc, 0x2e, 0x9d, 0xdf, 0x9b, 0x79, 0xef, 0xcd, 0x58, 0x43, 0xae, 0xd5, 0x82, 0xa5, 0xc2,
	0x2c, 0x65, 0x6a, 0x12, 0x88, 0x39, 0x83, 0x98, 0xcb, 0xcc, 0x68, 0x39, 0x5b, 0x19, 0x09, 0xe9,
	0x0b, 0x68, 0x2e, 0xf4, 0x48, 0x69, 0x30, 0x10, 0x76, 0xf3, 0xad, 0x23, 0xce, 0x60, 0xf0, 0x55,
	0x21, 0xbd, 0x71, 0xae, 0xfd, 0xc1, 0x76, 0x87, 0x94, 0xd4, 0x38, 0x83, 0x3b, 0xce, 0x35, 0x0d,
	0xfa, 0xc1, 0xb0, 0x31, 0x3d, 0xc1, 0xf0, 0x1f, 0x69, 0xd8, 0xe7, 0x12, 0x56, 0xa9, 0xa1, 0xbf,
	0xb0, 0x76, 0x26, 0x8e, 0xba, 0xa7, 0xcd, 0x64, 0x4c, 0xcb, 0x5e, 0x67, 0x61, 0x38, 0x20, 0x4d,
	0x99, 0xae, 0x45, 0x66, 0x40, 0xa3, 0x6d, 0x05, 0xcb, 0x05, 0x2e, 0xbc, 0x22, 0x6d, 0x8f, 0x5d,
	0xc0, 0x6f, 0xec, 0xba, 0x60, 0xf3, 0x5e, 0x18, 0x55, 0x2d, 0x7a, 0x61, 0x1e, 0x25, 0x35, 0x05,
	0x0a, 0xa3, 0x6a, 0x6e, 0x92, 0x23, 0xb4, 0x1b, 0xd8, 0xa7, 0x0b, 0xa8, 0xbb, 0x0d, 0x3c, 0x71,
	0xd4, 0xa1, 0x6d, 0xc3, 0xeb, 0xd0, 0xf1, 0x2f, 0xa9, 0xbf, 0x4a, 0x9d, 0x99, 0x47, 0x50, 0x94,
	0xf4, 0x83, 0x61, 0x79, 0xea, 0xb1, 0x55, 0x2d, 0x98, 0x2b, 0xfd, 0xc1, 0xd2, 0x09, 0x5a, 0x95,
	0xd2, 0xa0, 0x20, 0x13, 0x9a, 0x36, 0xd1, 0xd0, 0x63, 0xbb, 0x87, 0x60, 0x7a, 0xb1, 0x9d, 0xa4,
	0x6b, 0x1c, 0xb4, 0xe5, 0xf6, 0xc8, 0x73, 0xf6, 0x4f, 0x3c, 0x76, 0x23, 0xb7, 0xdd, 0x9f, 0x14,
	0xd9, 0xbc, 0x17, 0x0e, 0xdf, 0x29, 0x7a, 0xe1, 0x06, 0xff, 0x49, 0x2b, 0x33, 0x9a, 0x19, 0x91,
	0xc8, 0x39, 0x06, 0x76, 0xb1, 0xa9, 0x48, 0x86, 0x43, 0xd2, 0x39, 0x13, 0x2e, 0xb2, 0x87, 0x7d,
	0x97, 0x74, 0xc1, 0x0f, 0x43, 0xc3, 0x0b, 0x3f, 0x4b, 0xde, 0x4f, 0x3e, 0xf6, 0x51, 0xb0, 0xdb,
	0x47, 0xc1, 0xf7, 0x3e, 0x0a, 0xde, 0x0f, 0x51, 0x69, 0x77, 0x88, 0x4a, 0x9f, 0x87, 0xa8, 0xf4,
	0x1c, 0x27, 0xd2, 0xbc, 0xad, 0x66, 0xa3, 0x39, 0x2c, 0xe3, 0xf3, 0x61, 0xe6, 0x9e, 0x37, 0x09,
	0xc4, 0x1b, 0xbc, 0x68, 0xb3, 0x55, 0x22, 0x9b, 0x55, 0xf1, 0x8a, 0x6f, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x61, 0x1c, 0x03, 0x11, 0xf2, 0x02, 0x00, 0x00,
}

func (m *DistributionOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DistributionOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DistributionOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StrategicTxID) > 0 {
		i -= len(m.StrategicTxID)
		copy(dAtA[i:], m.StrategicTxID)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.StrategicTxID)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.StrategicAmount) > 0 {
		i -= len(m.StrategicAmount)
		copy(dAtA[i:], m.StrategicAmount)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.StrategicAmount)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.StrategicAddr) > 0 {
		i -= len(m.StrategicAddr)
		copy(dAtA[i:], m.StrategicAddr)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.StrategicAddr)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.EarlyInvTxID) > 0 {
		i -= len(m.EarlyInvTxID)
		copy(dAtA[i:], m.EarlyInvTxID)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.EarlyInvTxID)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.EarlyInvAmount) > 0 {
		i -= len(m.EarlyInvAmount)
		copy(dAtA[i:], m.EarlyInvAmount)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.EarlyInvAmount)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.EarlyInvAddr) > 0 {
		i -= len(m.EarlyInvAddr)
		copy(dAtA[i:], m.EarlyInvAddr)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.EarlyInvAddr)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Proposer) > 0 {
		i -= len(m.Proposer)
		copy(dAtA[i:], m.Proposer)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.Proposer)))
		i--
		dAtA[i] = 0x62
	}
	if m.LastPop != 0 {
		i = encodeVarintDistributionOrder(dAtA, i, uint64(m.LastPop))
		i--
		dAtA[i] = 0x58
	}
	if m.FirstPop != 0 {
		i = encodeVarintDistributionOrder(dAtA, i, uint64(m.FirstPop))
		i--
		dAtA[i] = 0x50
	}
	if len(m.PopTxID) > 0 {
		i -= len(m.PopTxID)
		copy(dAtA[i:], m.PopTxID)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.PopTxID)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.PopAmount) > 0 {
		i -= len(m.PopAmount)
		copy(dAtA[i:], m.PopAmount)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.PopAmount)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.PopAddr) > 0 {
		i -= len(m.PopAddr)
		copy(dAtA[i:], m.PopAddr)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.PopAddr)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.InvestorTxID) > 0 {
		i -= len(m.InvestorTxID)
		copy(dAtA[i:], m.InvestorTxID)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.InvestorTxID)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.InvestorAmount) > 0 {
		i -= len(m.InvestorAmount)
		copy(dAtA[i:], m.InvestorAmount)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.InvestorAmount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.InvestorAddr) > 0 {
		i -= len(m.InvestorAddr)
		copy(dAtA[i:], m.InvestorAddr)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.InvestorAddr)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DaoTxID) > 0 {
		i -= len(m.DaoTxID)
		copy(dAtA[i:], m.DaoTxID)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.DaoTxID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DaoAmount) > 0 {
		i -= len(m.DaoAmount)
		copy(dAtA[i:], m.DaoAmount)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.DaoAmount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DaoAddr) > 0 {
		i -= len(m.DaoAddr)
		copy(dAtA[i:], m.DaoAddr)
		i = encodeVarintDistributionOrder(dAtA, i, uint64(len(m.DaoAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDistributionOrder(dAtA []byte, offset int, v uint64) int {
	offset -= sovDistributionOrder(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DistributionOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DaoAddr)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.DaoAmount)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.DaoTxID)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.InvestorAddr)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.InvestorAmount)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.InvestorTxID)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.PopAddr)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.PopAmount)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.PopTxID)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	if m.FirstPop != 0 {
		n += 1 + sovDistributionOrder(uint64(m.FirstPop))
	}
	if m.LastPop != 0 {
		n += 1 + sovDistributionOrder(uint64(m.LastPop))
	}
	l = len(m.Proposer)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.EarlyInvAddr)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.EarlyInvAmount)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.EarlyInvTxID)
	if l > 0 {
		n += 1 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.StrategicAddr)
	if l > 0 {
		n += 2 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.StrategicAmount)
	if l > 0 {
		n += 2 + l + sovDistributionOrder(uint64(l))
	}
	l = len(m.StrategicTxID)
	if l > 0 {
		n += 2 + l + sovDistributionOrder(uint64(l))
	}
	return n
}

func sovDistributionOrder(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDistributionOrder(x uint64) (n int) {
	return sovDistributionOrder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DistributionOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDistributionOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DistributionOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DistributionOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DaoAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DaoAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaoTxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DaoTxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvestorAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvestorAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvestorAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvestorAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InvestorTxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InvestorTxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PopAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PopAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PopAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PopAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PopTxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PopTxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstPop", wireType)
			}
			m.FirstPop = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstPop |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastPop", wireType)
			}
			m.LastPop = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastPop |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarlyInvAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarlyInvAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarlyInvAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarlyInvAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarlyInvTxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarlyInvTxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StrategicAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StrategicAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StrategicAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StrategicAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StrategicTxID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StrategicTxID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDistributionOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDistributionOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDistributionOrder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDistributionOrder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDistributionOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDistributionOrder
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDistributionOrder
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDistributionOrder
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDistributionOrder        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDistributionOrder          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDistributionOrder = fmt.Errorf("proto: unexpected end of group")
)
