version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    nakedret:
      max-func-lines: 100
    tagalign:
      strict: true
    tagliatelle:
      case:
        rules:
          json: kebab
        use-field-name: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: x/.*/types/message.*\.go
      - linters:
          - dupl
        path: x/dao/client/cli/query_.*\.go
      - linters:
          - dupl
        path: x/dao/client/cli/tx_reissue_rddl.*\.go
      - linters:
          - revive
        path: x/dao/client/cli/*\.go
      - linters:
          - exhaustive
        path: testutil/nullify/nullify\.go
      - linters:
          - dupl
          - paralleltest
        path: x/.*/keeper/query.*\.go
      - linters:
          - paralleltest
        path: tests/.*/*\.go
      - linters:
          - paralleltest
        path: util/machine_nft_test\.go
      - linters:
          - gocognit
          - gocyclo
          - nestif
          - wastedassign
        path: testutil/network/network.go
      - linters:
          - revive
        path: x/.*/simulation/.*\.go
      - linters:
          - revive
        path: x/.*/module_simulation\.go
      - linters:
          - revive
        path: x/.*/client/cli/query_params\.go
      - linters:
          - revive
        path: x/.*/.*/cli/query_.*\.go
      - linters:
          - revive
        path: docs/docs\.go
      - linters:
          - paralleltest
        path: util/elementsd_connector_test\.go
      - linters:
          - paralleltest
        path: monitor/mqtt_monitor_test\.go
      - linters:
          - durationcheck
        path: monitor/.*\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
