---
run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - forbidigo
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
issues:
  exclude-rules:
    - path: codec\.go
      linters:
        - nosnakecase
    - path: app\/simulation_test\.go
      linters:
        - nosnakecase
    - path: testutil\/rest\.go
      linters:
        - nosnakecase
