---
version: 1
build:
  main: cmd/planetmint-god
accounts:
  - name: alice
    coins:
      - 20000plmnt
      - 200000000stake
  - name: bob
    coins:
      - 100000000plmnt
      - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 100000000plmnt
    - 100000stake
validators:
  - name: alice
    bonded: 100000000stake
