#! /usr/bin/make -f

## vet: Run go vet.
vet:
	@echo Running go vet...
	@go vet ./...

## fmt: Run go fmt.
fmt:
	@echo Running go fmt...
	@go fmt ./...

## build: Run go build.
build: vet fmt
	@echo Running go build...
	@go build -v ./...

## install: Run go install.
install: vet fmt
	@echo Running go install...
	@go install ./...
